### ISSUE TITLE
LauncherHelper - win32gui missing 

### ISSUE THREAD

**Issue by moomy94** [AlpineFrostSC/SCFileTools#3]
the requirements should include win32gui

**Comment by moomy94** [comment]
in case win32gui cannot be installed, **pywin32** works

**Comment by AlpineFrostSC** [comment]
yep! pywin32 includes all of the "win32..." modules used here
Added that to the requirements

Fixed by [812da51](https://github.com/AlpineFrostSC/SCFileTools/commit/812da51547a46d9a497a985bb5c6c54a299fd06cl)
